#pragma once

#include <stdlib.h>
#include <unity.h>
#include "mbed.h"

#define NEW_COMMON

#ifndef NEW_COMMON
#include "common/crypto/kerl/kerl.h"
#include "common/helpers/sign.h"
#include "common/model/transaction.h"
#include "common/trinary/tryte.h"
#include "utils/input_validators.h"
#else
#include "model/address.h"
#include "model/transaction.h"
#endif

char const expected_addr1[3][NUM_TRITS_HASH] = {
    "VZWHMT9AVBAKURC9FTEEPNUCMXPF9CFGWOUSKLZOUUCCEFOCPYTRVEISKXR9EDCAWKDHIEZ9UNZWVXAT9",
    "NSLSHMPXTMZRJHNXCBJMB9QWUJ9NWCMNWAPBCIN9YWU9NSIZDHXJCUKIQNDMBOVTEPMMJQTAKHENXS9NW",
    "TGPKCDBYRZSIQUMQ9WGIBISYOCSIWURTBDVOOZ9PVCABNABPIDT9JYNAINCBKGKQCMLXRSTGJZDAJ9ZGC"};

char const expected_addr2[3][NUM_TRITS_HASH] = {
    "XUERGHWTYRTFUYKFKXURKHMFEVLOIFTTCNTXOGLDPCZ9CJLKHROOPGNAQYFJEPGK9OKUQROUECBAVNXRX",
    "RJBYLCIOUKWJVCUKZQZCPIKNBUOGRGVXHRTTE9ZFSCGTFRKELMJBDDAKEYYCLHLJDNSHQ9RTIUIDLMUOB",
    "G9IBAWCWWYOSAVURTPX9JKBJLAFFBHWLOONFHTNENHJZGRLTDUDTMXTMBKYODOVHTAYKKIZBDGVAJJQJD"};

char const expected_addr3[3][NUM_TRITS_HASH] = {
    "REUJ9MRUHEGDYDPRQEUQHGFBLACFNNIAOHJA9IQGP9BOTJQZMSIIPJOBFFOOPKIBDNIAEXEHBPMITKIDZ",
    "LWGJJWWNGXEPLBVUGYRTUIIKXPVYSGKU9DMOAPSKUAAKC9H9XBLXAPLFEMBAODVZFIESFNLUCMPEINTOW",
    "FWHDJGG9TPLLWXSDNLDTOSISYCECGXUEKMEIDZUGUDKZHG9DFVGMVNFZVEBMQEOBIGQGDPOJGEHWVECGD"};